export const CREATE_TRIP = 'CREATE_TRIP'
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS'
export const CREATE_TRIP_ERROR = 'CREATE_TRIP_ERROR'

export const CREATE_USER_TRIP = 'CREATE_USER_TRIP'
export const CREATE_USER_TRIP_SUCCESS = 'CREATE_USER_TRIP_SUCCESS'
export const CREATE_USER_TRIP_ERROR = 'CREATE_USER_TRIP_ERROR'

export const UPDATE_TRIP = 'UPDATE_TRIP'
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS'
export const UPDATE_TRIP_ERROR = 'UPDATE_TRIP_ERROR'

export const UPDATE_USER_TRIP = 'UPDATE_USER_TRIP'
export const UPDATE_USER_TRIP_SUCCESS = 'UPDATE_USER_TRIP_SUCCESS'
export const UPDATE_USER_TRIP_ERROR = 'UPDATE_USER_TRIP_ERROR'

export const DELETE_TRIP = 'DELETE_TRIP'
export const DELETE_TRIP_SUCCESS = 'DELETE_TRIP_SUCCESS'
export const DELETE_TRIP_ERROR = 'DELETE_TRIP_ERROR'

export const DELETE_USER_TRIP = 'DELETE_USER_TRIP'
export const DELETE_USER_TRIP_SUCCESS = 'DELETE_USER_TRIP_SUCCESS'
export const DELETE_USER_TRIP_ERROR = 'DELETE_USER_TRIP_ERROR'
